# Generated by Django 4.0 on 2021-12-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='photography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Camera_name', models.CharField(max_length=100, null=True)),
                ('Camera_price', models.IntegerField(max_length=10, null=True)),
            ],
        ),
    ]
