# Generated by Django 3.0.8 on 2020-07-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gauranj', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('middlename', models.CharField(max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('reenterpassword', models.CharField(max_length=50, null=True)),
                ('DOB', models.CharField(max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
