# Generated by Django 3.0.8 on 2020-07-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gauranj', '0003_empblog'),
    ]

    operations = [
        migrations.CreateModel(
            name='comblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('middle_name', models.CharField(max_length=25, null=True)),
            ],
        ),
    ]
