# Generated by Django 3.0.8 on 2020-08-27 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gauranj', '0006_auto_20200803_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='comblog',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gauranj.empblog'),
        ),
        migrations.AddField(
            model_name='empblog',
            name='blogs',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='gauranj.comblog'),
        ),
    ]
