# Generated by Django 3.0.8 on 2020-09-02 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gauranj', '0007_auto_20200827_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('roll_no', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='university',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universityname', models.CharField(max_length=25, null=True)),
                ('stu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gauranj.student')),
            ],
        ),
    ]
