# Generated by Django 3.0.8 on 2020-09-03 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gauranj', '0008_student_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('surname', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentname', models.CharField(max_length=25, null=True)),
                ('kid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gauranj.child')),
            ],
        ),
    ]
