# Generated by Django 3.0.8 on 2020-09-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gauranj', '0010_subjects_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentsname', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='student_data', to='gauranj.StudentMany'),
        ),
    ]
