# Generated by Django 3.0.8 on 2020-09-09 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gauranj', '0012_auto_20200909_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='departmentsnumber',
        ),
    ]
