# Generated by Django 3.0.8 on 2020-09-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gauranj', '0016_temp1'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
