# Generated by Django 3.0.8 on 2020-09-16 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gauranj', '0017_temp_is_delete'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Temp1',
            new_name='Temp2',
        ),
    ]
