# Generated by Django 3.0.8 on 2020-09-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gauranj', '0018_auto_20200916_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp2',
            name='is_delete',
            field=models.BooleanField(null=True),
        ),
    ]
