# Generated by Django 3.0.8 on 2020-09-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gauranj', '0020_temp3'),
    ]

    operations = [
        migrations.CreateModel(
            name='practiceblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('middlename', models.CharField(max_length=25, null=True)),
                ('lastname', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Temp2',
        ),
        migrations.DeleteModel(
            name='Temp3',
        ),
    ]
