# Generated by Django 3.0.8 on 2020-10-02 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gauranj', '0023_registration_practice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration_practice',
            name='age',
        ),
        migrations.RemoveField(
            model_name='registration_practice',
            name='dateofbirth',
        ),
    ]
