# Generated by Django 3.0.8 on 2020-10-05 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gauranj', '0024_auto_20201002_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='student',
        ),
        migrations.AddField(
            model_name='teacher',
            name='sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gauranj.subjects'),
        ),
    ]
