# Generated by Django 3.0.8 on 2021-11-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gauranj', '0026_cruddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=8, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
