# Generated by Django 3.0.8 on 2021-11-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gauranj', '0027_blog1'),
    ]

    operations = [
        migrations.CreateModel(
            name='company1blogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('middlename', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('reenterpassword', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
